name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    
    - name: Set Up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Login to Docker Hub
      run: echo "${{ secrets.DOCKER_HUB_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_HUB_USERNAME }}" --password-stdin

    
    - name: Push Docker image to Docker Hub
      run: |
        COMMIT_SHA=$(git rev-parse --short HEAD)
        docker build -t devmaksdev/react-nginx-app:$COMMIT_SHA -t devmaksdev/react-nginx-app:latest .
        docker push devmaksdev/react-nginx-app:$COMMIT_SHA
        docker push devmaksdev/react-nginx-app:latest

  deploy:
    runs-on: ubuntu-latest
    needs: build

    steps:
    - name: Decode EC2 Private Key
      run: |
        echo "${{ secrets.EC2_PEM_KEY_BASE64 }}" | base64 -d > /tmp/ec2_key.pem
        chmod 600 /tmp/ec2_key.pem 

    - name: SSH into EC2 and Deploy
      uses: appleboy/ssh-action@v0.1.1
      with:
        host: ${{ secrets.EC2_HOST }}    
        username: ubuntu                 
        key: /tmp/ec2_key.pem            
        script: |
          docker pull devmaksdev/react-nginx-app
          docker stop react-app || true
          docker rm react-app || true
          docker run -d -p 80:80 --name react-app devmaksdev/react-nginx-app
