name: CI/CD Pipeline

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    
    - name: Set Up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Login to Docker Hub
      run: echo "${{ secrets.DOCKER_HUB_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_HUB_USERNAME }}" --password-stdin

    - name: Push Docker image to Docker Hub
      run: |
        COMMIT_SHA=$(git rev-parse --short HEAD)
        docker build -t devmaksdev/react-nginx-app:$COMMIT_SHA -t devmaksdev/react-nginx-app:latest \
          --build-arg REACT_APP_GITHUB_API_URL=${{vars.REACT_APP_GITHUB_API_URL}} \
          --build-arg REACT_APP_GITHUB_PERSONAL_ACCESS_TOKEN=${{vars.REACT_APP_GITHUB_PERSONAL_ACCESS_TOKEN}} \
          --build-arg REACT_APP_ENV=production \
          .
        docker push devmaksdev/react-nginx-app:$COMMIT_SHA
        docker push devmaksdev/react-nginx-app:latest

    - name: Install SSH key
      uses: webfactory/ssh-agent@v0.5.3
      with:
        ssh-private-key: ${{ secrets.EC2_SSH_KEY }}
    
    - name: Deploy Docker image to EC2
      run: |
        ssh -o StrictHostKeyChecking=no ${{ secrets.EC2_USER }}@${{vars.EC2_PUBLIC_API }} << 'EOF'
        docker pull devmaksdev/react-nginx-app
        docker stop $(docker ps -a -q) || true
        docker rm $(docker ps -a -q) || true
        docker run -d -p 80:80 --name react-app devmaksdev/react-nginx-app
        EOF
